# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_osx
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug_osx)
  TARGETDIR = bin
  TARGET = $(TARGETDIR)/wukongbase
  define BUILDCMDS
	@echo Running build commands
	premake5 --file=./wukong_base/wukongbase.lua --cc=clang gmake
	make -C wukong_base config=debug_osx target=wukongbase
  endef
  define CLEANCMDS
	@echo Running clean commands
	make -C wukong_base clean
	rm -rf wukong_base/bin
  endef
endif

ifeq ($(config),release_osx)
  TARGETDIR = bin
  TARGET = $(TARGETDIR)/wukongbase
  define BUILDCMDS
	@echo Running build commands
	premake5 --file=./wukong_base/wukongbase.lua --cc=clang gmake
	make -C wukong_base config=release_osx target=wukongbase
  endef
  define CLEANCMDS
	@echo Running clean commands
	make -C wukong_base clean
	rm -rf wukong_base/bin
  endef
endif

$(TARGET):
	$(BUILDCMDS)

clean:
	$(CLEANCMDS)
