# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug_osx
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_osx)
  wukongbase_config = debug_osx
  uv_config = debug_osx
endif
ifeq ($(config),release_osx)
  wukongbase_config = release_osx
  uv_config = release_osx
endif

PROJECTS := wukongbase uv

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

wukongbase: uv
ifneq (,$(wukongbase_config))
	@echo "==== Building wukongbase ($(wukongbase_config)) ===="
	@${MAKE} --no-print-directory -C . -f wukongbase.make config=$(wukongbase_config)
endif

uv:
ifneq (,$(uv_config))
	@echo "==== Building uv ($(uv_config)) ===="
	@${MAKE} --no-print-directory -C . -f uv.make config=$(uv_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f wukongbase.make clean
	@${MAKE} --no-print-directory -C . -f uv.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_osx"
	@echo "  release_osx"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   wukongbase"
	@echo "   uv"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"